classes:
- AG_Ammeter03_AC_NA
- AG_Pressure01_NA_NA
- AG_Pressure02_NA_NA
- AG_Pressure03_NA_NA
- AG_Pressure04_NA_NA
- AG_Pressure05_NA_NA
- AG_Pressure06_NA_NA
- AG_Pressure07_NA_NA
- AG_Pressure_Fire-extingusher_NA
- AG_Temperature_NA_NA
- AG_Thermo-hygro_NA_NA
- DG_ACV-DCV-OCA_V-V-A_NA
- DG_Boost-pump_bar_NA
- DG_DC-Volt_V_NA
- DG_DMFR_NA_NA
- DG_Heater_Temp_NA
- DG_Pump_ME_NA
- DG_RST-RST_VVV-VVV-AAA_NA
- DG_TR-Temp_C_NA
- DG_Temp_Air-Conditioner_NA
- DG_VAP_Meter_NA
- DG_VA_NA_NA
- DG_Va-Ia-P-UH_V-A-P-Mwh_NA
- DG_pump_bar_NA
- Etc_Fire-Extinguisher_NA_NA
- Etc_Fire-Hydrant-sign_NA_NA
- Etc_Outlet_Aplug_ok
- Etc_Outlet_No-plug_ok
- Etc_Person_hat_ok
- LED_DMFR_Run-on_ok
- LED_Green-dot_on_ok
- LED_Green_off_ok
- LED_Green_on_ok
- LED_Leakage_Green-on_ok
- LED_PD-Detector_off_ok
- LED_PD_on_ok
- LED_Panel-green-dot_off_ok
- LED_Panel-red-dot_on_ok
- LED_Panel_off_ok
- LED_Red-dot_on_ok
- LED_Red_off_ok
- LED_Red_on_ok
- LED_Yellow_off_ok
- Sw_Nobe-dot_Left_ok
- Sw_Nobe-dot_Right_ok
- Sw_Nobe_Left_ok
- Sw_Nobe_Right_ok
- Sw_Pump_Left_ok
- Sw_Pump_Right_ok
- Sw_Round-dot_Left_ok
- Sw_Round_Right_nok
- Valve_Valve_Closed_ok
- Valve_Valve_Opened_ok
confidence_threshold: 0.45
config_file: /home/kiie/projects/xanylabeling/test/trains/Total_runs/xany_config.yaml
display_name: DS_P2_Tr4 (53 classes)
input_height: 1024
input_width: 1024
model_path: weights/best.onnx
name: custom_Total_runs
nms_threshold: 0.45
score_threshold: 0.5
type: yolov8
