"""도메인 규칙 — LABEL_MAP, VLM_PROMPTS, 판정 임계값"""

LABEL_MAP = {
    "A": ["B", "c", "d", "f", "g", "h"],
    "AG_Ammeter01_A-0-300": ["AG_Ammeter01_AC_NA", "AG_Ammeter02_AC_NA", "AG_Ammeter03_AC_NA", "AG_Ammeter04_AC_NA"],
    "AG_Ammeter02_A-0-30": ["AG_Ammeter01_AC_NA", "AG_Ammeter02_AC_NA", "AG_Ammeter03_AC_NA", "AG_Ammeter04_AC_NA"],
    "AG_Ammeter03_A-0-100": ["AG_Ammeter01_AC_NA", "AG_Ammeter02_AC_NA", "AG_Ammeter03_AC_NA", "AG_Ammeter04_AC_NA"],
    "AG_Ammeter04_A-0-100": ["AG_Ammeter01_AC_NA", "AG_Ammeter02_AC_NA", "AG_Ammeter03_AC_NA", "AG_Ammeter04_AC_NA"],
    "AG_Pressure_Fire-extinguisher": ["AG_Pressure_Fire-extinguisher", "AG_Pressure_Fire-extingusher", "AG_Pressure_Fire-extingusher_NA", "AG_Pressure_Fire-extinguisher_NA"],
    "AG_Pressure01_P-0-1": ["AG_Pressure01_NA_NA", "AG_Pressure02_NA_NA", "AG_Pressure03_NA_NA", "AG_Pressure04_NA_NA", "AG_Pressure05_NA_NA", "AG_Pressure06_NA_NA", "AG_Pressure07_NA_NA"],
    "AG_Pressure02_P-0-1.5": ["AG_Pressure01_NA_NA", "AG_Pressure02_NA_NA", "AG_Pressure03_NA_NA", "AG_Pressure04_NA_NA", "AG_Pressure05_NA_NA", "AG_Pressure06_NA_NA", "AG_Pressure07_NA_NA"],
    "AG_Pressure03_P-0-1.5": ["AG_Pressure01_NA_NA", "AG_Pressure02_NA_NA", "AG_Pressure03_NA_NA", "AG_Pressure04_NA_NA", "AG_Pressure05_NA_NA", "AG_Pressure06_NA_NA", "AG_Pressure07_NA_NA"],
    "AG_Pressure04_P-0-1.5": ["AG_Pressure01_NA_NA", "AG_Pressure02_NA_NA", "AG_Pressure03_NA_NA", "AG_Pressure04_NA_NA", "AG_Pressure05_NA_NA", "AG_Pressure06_NA_NA", "AG_Pressure07_NA_NA"],
    "AG_Pressure05_P-0-16": ["AG_Pressure01_NA_NA", "AG_Pressure02_NA_NA", "AG_Pressure03_NA_NA", "AG_Pressure04_NA_NA", "AG_Pressure05_NA_NA", "AG_Pressure06_NA_NA", "AG_Pressure07_NA_NA"],
    "AG_Pressure06_P-0-1.5": ["AG_Pressure01_NA_NA", "AG_Pressure02_NA_NA", "AG_Pressure03_NA_NA", "AG_Pressure04_NA_NA", "AG_Pressure05_NA_NA", "AG_Pressure06_NA_NA", "AG_Pressure07_NA_NA"],
    "AG_Pressure07_P-0-2": ["AG_Pressure01_NA_NA", "AG_Pressure02_NA_NA", "AG_Pressure03_NA_NA", "AG_Pressure04_NA_NA", "AG_Pressure05_NA_NA", "AG_Pressure06_NA_NA", "AG_Pressure07_NA_NA"],
    "AG_Temperature_T-0-100": ["AG_Temperature_NA_NA"],
    "AG_Thermo-hygro": ["AG_Thermo-hygro_NA_NA"],
    "AG_Voltimeter_V-0-30": ["AG_Voltimeter_AC_NA"],
    "Class_C-Duct_Clean_ok": ["Class_C-Duct_Clean_ok"],
    "Class_D-Gen_No-oil_ok": ["Class_D-Gen_No-oil_ok"],
    "Class_Plumb_Clean_ok": ["Class_Plumb_Clean_ok"],
    "Class_W-Drains_Clean_ok": ["Class_W-Drains_Clean_ok"],
    "Class_W-Tank_Gauge_ok": ["Class_W-Tank_Gauge_ok"],
    "DG_Air-Conditioner": ["DG_Temp_Air-Conditioner_NA"],
    "DG_GIMAC-DC": ["DG_ACV-DCV-OCA_V-V-A_NA"],
    "DG_BMS": [""],
    "DG_Boost-pump": ["DG_Boost-pump_bar_NA"],
    "DG_Digital-Integrated-Meter": ["DG_Va-Ia-P-UH_V-A-P-Mwh_NA"],
    "DG_Digital-Meter": ["DG_VAP_Meter_NA"],
    "DG_UPS-600KVA": ["DG_VA_NA_NA"],
    "DG_Electric-Water-Heater": ["DG_Heater_Temp_NA"],
    "DG_Gen-Status": ["DG_Gen-Status_Alt-Eng_NA"],
    "DG_PB_max": ["DG_PB-Demend_R_NA"],
    "DG_Pump": ["DG_Pump_ME_NA"],
    "DG_Thermo-hygro": ["DG_Temp-Humi01_C-per_NA", "DG_Temp-Humi02_C-per_NA"],
    "DG_TR-temp": ["DG_Tr-Temp_C_NA", "DG_Pump_ME_NA"],
    "DG_UPS_100KVA": ["DG_RST-RST_VVV-VVV-AAA_NA"],
    "DG_UPS_600KVA": ["DG_VA_NA_NA"],
    "ETC_Fire_Extinguisher": ["Etc_Fire-Extinguisher_NA_NA"],
    "ETC_Fire_Hydrant-sign": ["Etc_Fire-Hydrant-sign_NA_NA"],
    "Class_Outlet": ["Etc_Outlet_No-plug_ok"],
    "LED_DELD_PAB-on": ["LED_Leakage_Green-on_ok", "LED_DELD_run-on"],
    "LED_DMFR_run-on": ["LED_DMFR_Run-on_ok", "LED_DMFR_run-on_nok"],
    "LED_Controller": [""],
    "LED_Green": ["LED_Green_off", "LED_Green_off_ok", "LED_Green_on", "LED_Green_on_ok"],
    "LED_Green_off": ["LED_Green_off_nok", "LED_Green_off_ok"],
    "LED_Green_on": ["LED_Green_on_nok", "LED_Green_on_ok"],
    "LED_Green-dot": ["LED_Green-dot_off_nok", "LED_Green-dot_off_ok", "LED_Green-dot_on_nok", "LED_Green-dot_on_ok"],
    "LED_Green-dot_off": ["LED_Green-dot_off_nok", "LED_Green-dot_off_ok"],
    "LED_Green-dot_on": ["LED_Green-dot_on_nok", "LED_Green-dot_on_ok"],
    "LED_Panel": ["LED_Panel_off_ok", "LED_Panel_off_nok", "LED_Panel_on_ok", "LED_Panel_on_nok"],
    "LED_Panel_off": ["LED_Panel_off_ok", "LED_Panel_off_nok"],
    "LED_Panel_on": ["LED_Panel_on_ok", "LED_Panel_on_nok"],
    "LED_Panel-green-dot": ["LED_Panel-green-dot_on_ok", "LED_Panel-green-dot_on_nok", "LED_Panel-green-dot_off_ok", "LED_Panel-green-dot_off_nok"],
    "LED_Panel-green-dot_off": ["LED_Panel-green-dot_off_ok", "LED_Panel-green-dot_off_nok"],
    "LED_Panel-green-dot_on": ["LED_Panel-green-dot_on_ok", "LED_Panel-green-dot_on_nok"],
    "LED_Panel-red-dot": ["LED_Panel-red-dot_on_ok", "LED_Panel-red-dot_on_nok", "LED_Panel-red-dot_off_ok", "LED_Panel-red-dot_off_nok"],
    "LED_Panel-red-dot_off": ["LED_Panel-red-dot_off_ok", "LED_Panel-red-dot_off_nok"],
    "LED_Panel-red-dot_on": ["LED_Panel-red-dot_on_ok", "LED_Panel-red-dot_on_nok"],
    "LED_pd": ["LED_PD_on_ok", "LED_PD_on_nok", "LED_PD_off_ok", "LED_PD_off_nok"],
    "LED_PD_off": ["LED_PD_off_ok", "LED_PD_off_nok"],
    "LED_PD_on": ["LED_PD_on_ok", "LED_PD_on_nok"],
    "LED_Red": ["LED_Red_off", "LED_Red_off_ok", "LED_Red_on", "LED_Red_on_ok"],
    "LED_Red_off": ["LED_Red_off"],
    "LED_Red_on": ["LED_Red_on_nok", "LED_Red_on_ok"],
    "LED_Red-dot": ["LED_Red-dot_off_nok", "LED_Red-dot_off_ok", "LED_Red-dot_on_nok", "LED_Red-dot_on_ok"],
    "LED_Red-dot_off": ["LED_Red-dot_off_nok", "LED_Red-dot_off_ok"],
    "LED_Red-dot_on": ["LED_Red-dot_on_nok", "LED_Red-dot_on_ok"],
    "LED_Yellow_off": ["LED_Yellow_off_ok", "LED_Yellow_off_nok"],
    "LED_Yellow_on": ["LED_Yellow_on_ok", "LED_Yellow_on_nok"],
    "Sw_Nobe": ["Sw_Nobe_Center", "Sw_Nobe_Left", "Sw_Nobe_Right"],
    "Sw_Nobe_Center": ["Sw_Nobe_Center_ok", "Sw_Nobe_Center_nok"],
    "Sw_Nobe_Left": ["Sw_Nobe_Left_ok", "Sw_Nobe_Left_nok"],
    "Sw_Nobe_Right": ["Sw_Nobe_Right_ok", "Sw_Nobe_Right_nok"],
    "Sw_Nobe-dot_Center": ["Sw_Nobe-dot_Center_ok", "Sw_Nobe-dot_Center_nok"],
    "Sw_Nobe-dot_Center_nok": ["Sw_Nobe-dot_Center_nok"],
    "Sw_Nobe-dot_Left": ["Sw_Nobe-dot_Left_ok", "Sw_Nobe-dot_Left_nok"],
    "Sw_Nobe-dot_Left_nok": ["Sw_Nobe-dot_Left_nok"],
    "Sw_Nobe-dot_Right": ["Sw_Nobe-dot_Right_ok", "Sw_Nobe-dot_Right_nok"],
    "Sw_Nobe-dot_Right_nok": ["Sw_Nobe-dot_Right_nok"],
    "Sw_Pump": ["Sw_Pump_Left", "Sw_Pump_Center", "Sw_Pump_Right"],
    "Sw_Pump_Center": ["Sw_Pump_Center"],
    "Sw_Pump_Left": ["Sw_Pump_Left"],
    "Sw_Pump_Right": ["Sw_Pump_Right"],
    "Sw_Round_Center": ["Sw_Round_Center"],
    "Sw_Round_Left": ["Sw_Round_Left"],
    "Sw_Round_Right": ["Sw_Round_Right"],
    "Sw_Round-dot_Center": ["Sw_Round-dot_Center"],
    "Sw_Round-dot_Left": ["Sw_Round-dot_Left"],
    "Sw_Round-dot_Right": ["Sw_Round-dot_Right"],
    "Sw_Valve_Closed": ["Valve_Valve_Closed_ok", "Valve_Valve_Opened_ok"],
    "Sw_Valve_Opened": ["Valve_Valve_Closed_ok", "Valve_Valve_Opened_ok"],
    "Sw_Valve": ["Sw_Valve_Closed", "Sw_Valve_Opened"],
    "Class_C-Duct_Clean": ["Class_C-Duct_Clean"],
    "Class_Clean": ["Class_Clean"],
    "Class_Plumb_Clean": ["Class_Plumb_Clean"],
    "Class_W-Tank_Gauge": ["Class_W-Tank_Gauge"],
    "Class_Water_Clean": ["Class_Water_Clean"],
}

VLM_PROMPTS = {
    "Class_C-Duct": """Write in 3 lines. English only. No reason.
        1) Cleaning State(1~5):
        2) Leakage(O/X):
        3) Corrosion(O/X):""",
    "Class_Pipe_condition": """Write in 1 line. English only. No reason.
        1) Insulation State(Good/Poor):""",
    "Class_Water_level_gauge": """Write in 2 lines. English only. No reason.
        1) Leakage(O/X):
        2) Damage(O/X):""",
    "Class_Outlet": """Write in 1 line. English only. No reason.
        1) Outlet Condition(Good/Poor):""",
    "Class_Wire_condition": """Write in 1 line. English only. No reason.
        1) Abnormality(Good/Poor):""",
    "Class_Fire": """Write in 2 lines. English only. No reason.
        1) Location(Normal/Abnormal):
        2) Fire-extinguisher State(Good/Poor):""",
    "Class_Clean": """Write in 1 line. English only. No reason.
        1) Cleaning State(Good/Poor):""",
    "DG_Air-Conditioner": "Read the green number. Output format: (Number). Example: (24). No other text.",
    "DG_Gen-Status": "Read the Coolant Temp number. Output format: (Number). Example: (85). No other text.",
    "DG_Electric-Water-Heater": "Read the red number. Output format: (Number). Example: (45). No other text.",
    "DG_Pump": "Read the number. Output format: (Number). Example: (3.5). No other text.",
    "DG_BMS": "1 line only. Fixed format. No explanation. If Top-Right shows Normal operation write 'Normal', else 'Abnormal'. No other text.",
    "DG_TR-temp": "Read the actual PEAK and Temp. Controller numbers from the image. Output format: (PEAK|Temp). Format Example: (999|99.9). Do not copy the example, read the real values. No other text.",
    "DG_Digital-Integrated-Meter": "Read the actual Va, Ia, P, WH values from the image. Output format: (Va|Ia|P|WH). Format Example: (999|99|99|9999). Do not copy the example, read the real values. No other text.",
    "DG_GIMAC-DC": "Read the actual Top, Middle, Bottom numbers from the image. Output format: (Top|Middle|Bottom). Format Example: (999|99|999). Do not copy the example, read the real values. No other text.",
    "DG_PB-max": "Read the actual 4 large numbers in columns from the image. Output format: (Col1|Col2|Col3|Col4). Format Example: (999|999|999|999). Do not copy the example, read the real values. No other text.",
    "DG_Thermo-hygro": "Read the actual Temp and Humidity from the image. Output format: (Temp|Humidity). Format Example: (99.9|99). Do not copy the example, read the real values. No other text.",
    "DG_Digital-Meter": "Read Top, Middle, Bottom red numbers 1 lines only. No explanation. if not detected NaN. Output format: (Top| Middle| Bottom)",
    "DG_Boost-pump": "Read the actual Set Pressure and Current Pressure inside the circle from the image. Output format: (Set|Current). Format Example: (9.9|9.9). Do not copy the example, read the real values. No other text.",
    "DG_UPS-100KVA": "Read Input V(R,S,T), Input A(R,S,T), Output V(R,S,T), Output A(R,S,T), Bypass V(R,S,T), Battery V, Battery A. Output format: (InputV_R, InputV_S, InputV_T, InputA_R, InputA_S, InputA_T, OutputV_R, OutputV_S, OutputV_T, OutputA_R, OutputA_S, OutputA_T, BypassV_R, BypassV_S, BypassV_T, BattV, BattA). Example: (220, 220, 220, 10, 10, 10, 220, 220, 220, 10, 10, 10, 220, 220, 220, 500, 10). Separator: Comma. Forbidden: Semicolon. No other text.",
    "DG_UPS-600KVA": "Read Input V(R,S,T), Input A(R,S,T), Output V(R,S,T), Output A(R,S,T), Bypass V(R,S,T), SOC %, Batt V, Batt A. Output format: (InputV_R, InputV_S, InputV_T, InputA_R, InputA_S, InputA_T, OutputV_R, OutputV_S, OutputV_T, OutputA_R, OutputA_S, OutputA_T, BypassV_R, BypassV_S, BypassV_T, SOC, BattV, BattA). No other text.",
    "DEFAULT": "Describe the equipment state in 1-2 lines. English only. Focus on damage or abnormality.",
}

COLORS = {
    "PASS": (0, 255, 0),
    "FAIL": (0, 0, 255),
    "UNKNOWN": (0, 255, 255),
    "OUTLINE": (0, 0, 0),
}

STATUS_MAPPING = {
    "on": "on", "off": "off", "open": "open", "close": "close",
    "run": "run", "stop": "stop", "trip": "trip", "fault": "fault",
}
